import Foundation

/// Represents a single schema migration with up (forward) and down (rollback) SQL.
public struct Migration: Sendable, Codable, Equatable {
    /// Unique identifier (timestamp + description slug), e.g. "20260403_143000_add_users_index"
    public let id: String
    /// Human-readable description of the migration
    public let description: String
    /// ISO 8601 timestamp when this migration was generated
    public let generatedAt: String
    /// SHA-256 checksum of the SQL file contents
    public var checksum: String
    /// Object identifiers affected by this migration
    public let objectsAffected: [String]
    /// Changes that cannot be reversed (e.g. enum value additions)
    public let irreversibleChanges: [String]
    /// Metadata format version
    public let version: Int

    public init(
        id: String,
        description: String,
        generatedAt: String,
        checksum: String,
        objectsAffected: [String] = [],
        irreversibleChanges: [String] = [],
        version: Int = 1
    ) {
        self.id = id
        self.description = description
        self.generatedAt = generatedAt
        self.checksum = checksum
        self.objectsAffected = objectsAffected
        self.irreversibleChanges = irreversibleChanges
        self.version = version
    }
}

/// The parsed content of a migration SQL file, split into sections.
public struct MigrationSQL: Sendable, Equatable {
    public let upSQL: String
    public let downSQL: String
    public let customUpSQL: String
    public let customDownSQL: String
    public let dataUpSQL: String
    public let dataDownSQL: String

    public init(
        upSQL: String,
        downSQL: String,
        customUpSQL: String = "",
        customDownSQL: String = "",
        dataUpSQL: String = "",
        dataDownSQL: String = ""
    ) {
        self.upSQL = upSQL
        self.downSQL = downSQL
        self.customUpSQL = customUpSQL
        self.customDownSQL = customDownSQL
        self.dataUpSQL = dataUpSQL
        self.dataDownSQL = dataDownSQL
    }

    /// Full forward SQL: schema up + custom up + data up
    public var fullUpSQL: String {
        [upSQL, customUpSQL, dataUpSQL]
            .filter { !$0.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty }
            .joined(separator: "\n\n")
    }

    /// Full rollback SQL: data down + custom down + schema down
    public var fullDownSQL: String {
        [dataDownSQL, customDownSQL, downSQL]
            .filter { !$0.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty }
            .joined(separator: "\n\n")
    }

    /// Render as a complete SQL file with section markers.
    public func render(migrationId: String) -> String {
        var lines: [String] = []
        lines.append("-- Migration: \(migrationId)")
        lines.append("-- Generated by pg-schema-evo")
        lines.append("")
        lines.append("-- === UP ===")
        lines.append(upSQL)
        lines.append("")
        lines.append("-- === DOWN ===")
        lines.append(downSQL)
        if !customUpSQL.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            lines.append("")
            lines.append("-- === CUSTOM UP ===")
            lines.append(customUpSQL)
        }
        if !customDownSQL.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            lines.append("")
            lines.append("-- === CUSTOM DOWN ===")
            lines.append(customDownSQL)
        }
        if !dataUpSQL.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            lines.append("")
            lines.append("-- === DATA UP ===")
            lines.append(dataUpSQL)
        }
        if !dataDownSQL.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            lines.append("")
            lines.append("-- === DATA DOWN ===")
            lines.append(dataDownSQL)
        }
        lines.append("")
        return lines.joined(separator: "\n")
    }

    /// Parse a SQL file with section markers back into a MigrationSQL struct.
    public static func parse(from content: String) -> MigrationSQL {
        var sections: [String: String] = [:]
        var currentSection: String?
        var currentLines: [String] = []

        for line in content.components(separatedBy: "\n") {
            if line.hasPrefix("-- === ") && line.hasSuffix(" ===") {
                if let section = currentSection {
                    sections[section] = currentLines.joined(separator: "\n")
                        .trimmingCharacters(in: .whitespacesAndNewlines)
                }
                currentSection = String(line.dropFirst(7).dropLast(4))
                currentLines = []
            } else if currentSection != nil {
                currentLines.append(line)
            }
        }
        if let section = currentSection {
            sections[section] = currentLines.joined(separator: "\n")
                .trimmingCharacters(in: .whitespacesAndNewlines)
        }

        return MigrationSQL(
            upSQL: sections["UP"] ?? "",
            downSQL: sections["DOWN"] ?? "",
            customUpSQL: sections["CUSTOM UP"] ?? "",
            customDownSQL: sections["CUSTOM DOWN"] ?? "",
            dataUpSQL: sections["DATA UP"] ?? "",
            dataDownSQL: sections["DATA DOWN"] ?? ""
        )
    }
}

/// Record of an applied migration stored in the tracking table.
public struct AppliedMigration: Sendable, Equatable {
    public let id: String
    public let checksum: String
    public let description: String
    public let appliedAt: Date
    public let appliedBy: String

    public init(id: String, checksum: String, description: String, appliedAt: Date, appliedBy: String) {
        self.id = id
        self.checksum = checksum
        self.description = description
        self.appliedAt = appliedAt
        self.appliedBy = appliedBy
    }
}

/// Configuration for the migration system.
public struct MigrationConfig: Sendable {
    /// Directory where migration files are stored
    public let directory: String
    /// Name of the tracking table on the target database
    public let trackingTable: String
    /// Schema for the tracking table
    public let trackingSchema: String

    public static let defaultDirectory = "migrations"
    public static let defaultTrackingTable = "_pg_schema_evo_migrations"
    public static let defaultTrackingSchema = "public"

    public init(
        directory: String = Self.defaultDirectory,
        trackingTable: String = Self.defaultTrackingTable,
        trackingSchema: String = Self.defaultTrackingSchema
    ) {
        self.directory = directory
        self.trackingTable = trackingTable
        self.trackingSchema = trackingSchema
    }

    /// Fully qualified tracking table name
    public var qualifiedTrackingTable: String {
        "\(trackingSchema).\(trackingTable)"
    }
}
